### Tensor definition

- **torch**: 메인 네임스페이스, 텐서 및 수학 함수 포함
- **torch.autograd**: 미분을 위한 함수 포함, 자동미분을 제어용 콘텍스트 매니저(`enable_grad`/`no_grad`) 및 미분 가능 함수 정의용 기반 클래스 `Function` 포함
- **torch.nn**: 신경망을 위한 데이터 구조 및 레이어 정의, `RNN`, `LSTM` 등의 레이어, `ReLU` 등 활성화 함수, `MSELoss` 등 손실함수 등이 포함
- **torch.optim**: `SGD` 및 파라미터 최적화 알고리즘 포함
- **torch.utils.data**: `mini-batch` 용 유틸함수 포함
- **torch.onnx**: `ONNX(Open Neural Network Exchange)`의 포맷(서로 다른 딥러닝 프레임워크간 모델 공유 포맷)으로 모델을 익스포트(export)할 때 사용

- **Scalar**: 차원이 없는 단일 값
- **Vector**: 1차원으로 구성된 값
- **Matrix**: 2차원으로 구성된 값, 행렬, 2차원 배열
- **Tensor**: 3차원 이상으로 구성된 값, 1차원/2차원 행렬도 텐서라 표현하기도 함

### Tensor Shape Convention

- **2D Tensor(Typical Simple Setting)**
  
  |t| = (batch size, dimension)

- **3D Tensor(Typical Computer Vision)**

  |t| = (batch size, width, height)

- **3D Tensor(Typical Natural Language Processing)**

  |t| = (batch size, length, dimension)

### Tensor with Numpy

In [137]:
import numpy as np

In [138]:
# 1D
t1 = np.array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
print(t1, t1[-1], t1[1:5])
print('rank', t1.ndim)
print('shape', t1.shape)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] 9.0 [1. 2. 3. 4.]
rank 1
shape (10,)


In [139]:
# 2D
t2 = np.array([[1., 2., 3.,], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t2)
print('rank', t2.ndim)
print('shape', t2.shape)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
rank 2
shape (4, 3)


In [140]:
# 3D
t3 = np.array([[[1., 2.], [3., 4.], [5., 6.]], [[7., 8.], [9., 10.], [11., 12.]], [[13., 14.], [15., 16.], [17., 18.]], [[19., 20.], [21., 22.], [23., 24.]]])
print(t3)
print('rank', t3.ndim)
print('shape', t3.shape)

[[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]

 [[13. 14.]
  [15. 16.]
  [17. 18.]]

 [[19. 20.]
  [21. 22.]
  [23. 24.]]]
rank 3
shape (4, 3, 2)


### Tensor with PyTorch

In [141]:
import torch

In [142]:
# 1D
t1 = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
print(t1, t1[-1], t1[1:5])
print('rank', t1.dim())
print('size', t1.size())
print('shape', t1.shape)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]) tensor(9.) tensor([1., 2., 3., 4.])
rank 1
size torch.Size([10])
shape torch.Size([10])


In [143]:
# 2D
t2 = torch.FloatTensor([[1., 2., 3.,], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t2)
print('rank', t2.dim())
print('size', t2.size())
print('shape', t2.shape)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
rank 2
size torch.Size([4, 3])
shape torch.Size([4, 3])


In [144]:
print(t2[:, 0], t2[:, 0].dim(), t2[:, 0].size())
print(t2[:, 1], t2[:, 1].dim(), t2[:, 1].size())
print(t2[:, 2], t2[:, 2].dim(), t2[:, 2].size())

tensor([ 1.,  4.,  7., 10.]) 1 torch.Size([4])
tensor([ 2.,  5.,  8., 11.]) 1 torch.Size([4])
tensor([ 3.,  6.,  9., 12.]) 1 torch.Size([4])


In [145]:
print(t2[:, :-1], t2[:, :-1].dim(), t2[:, :-1].size())
print(t2[:, :-2], t2[:, :-2].dim(), t2[:, :-2].size())
print(t2[:, 1:], t2[:, 1:].dim(), t2[:, 1:].size())
print(t2[:, 2:], t2[:, 2:].dim(), t2[:, 2:].size())

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]]) 2 torch.Size([4, 2])
tensor([[ 1.],
        [ 4.],
        [ 7.],
        [10.]]) 2 torch.Size([4, 1])
tensor([[ 2.,  3.],
        [ 5.,  6.],
        [ 8.,  9.],
        [11., 12.]]) 2 torch.Size([4, 2])
tensor([[ 3.],
        [ 6.],
        [ 9.],
        [12.]]) 2 torch.Size([4, 1])


### PyTorch Broadcasting

`Broadcasting` 연산에 사용되는 Tensor를 연산이 가능하도록 변환

In [146]:
# Vector + Vector
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [147]:
# Vector + Scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)

tensor([[4., 5.]])


In [148]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]]) # [[1, 2]] -> [[1, 2], [1, 2]]
m2 = torch.FloatTensor([[3], [4]]) # [[3], [4]] -> [[3, 3], [4, 4]]
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


### Matrix Multiplication / Multiplication

In [149]:
# normal matrix multiplication
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [150]:
# element-wise multiplication
# broadcasting -> matrix multiplication
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1 / [[1], [2]] -> [[1, 1], [2, 2]]
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### Mean

In [151]:
t = torch.FloatTensor([1, 2])
print(t)
print(t.mean())

tensor([1., 2.])
tensor(1.5000)


In [152]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.mean())

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)


In [153]:
print(t.mean(dim=0))
# t.mean(dim=0)은 입력에서 첫번째 차원을 제거, 즉 행이 제거, 1과 3의 평균을 구하고, 2와 4의 평균을 구한다.

tensor([2., 3.])


In [154]:
print(t.mean(dim=1))
# 두번째 차원을 제거, 즉 열이 제거, 1과 2의 평균을 구하고, 3과 4의 평균을 구한다.

tensor([1.5000, 3.5000])


In [155]:
print(t.mean(dim=-1))
# 마지막 차원을 제거, 여기에서는 열의 차원을 제거

tensor([1.5000, 3.5000])


### Sum

In [156]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [157]:
print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행을 제거
print(t.sum(dim=1)) # 열을 제거
print(t.sum(dim=-1)) # 열을 제거

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


### Max / ArgMax

- `Max` 텐서 사이에서 최대값
- `ArgMax` 최대값의 인덱스

In [158]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [159]:
print(t.max())
print(t.max(dim=0)) # 첫번째 차원을 제거, argmax도 함께 리턴

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [160]:
print('Max: ', t.max(dim=0)[0]) # 최댓값
print('Argmax: ', t.max(dim=0)[1]) # 최댓값의 인덱스

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [161]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


### View

`View` 는 PyTorch에서 Numpy의 `Reshape` 와 같은 역할, 즉 텐서의 크기(Shape)를 변경해주는 역할

- view는 변경 전과 변경 후의 텐서 안의 원소의 개수가 유지
- view는 사이즈가 -1로 설정되면 다른 차원으로부터 해당 값을 유추

In [162]:
t = np.array([[[0, 1, 2], [3, 4, 5]],
              [[6, 7, 8], [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft)
print(ft.shape)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([2, 2, 3])


In [163]:
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)
# -1은 첫번째 차원은 사용자가 잘 모르겠으니 파이토치에 맡기겠다는 의미, 3은 두번째 차원의 길이는 3을 가지도록 하라는 의미

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [164]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### Squeeze / Unsqueeze

`View` 와 마찬가지로 텐서의 원소 수를 그대로 유지하면서 모양과 차원을 조절
- `Squeeze` 차원이 1인 경우 제거
- `Unsqueeze` 특정 위치에 1인 차원을 추가

In [165]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.dim())
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
2
torch.Size([3, 1])


In [166]:
print(ft.squeeze())
print(ft.squeeze().dim())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
1
torch.Size([3])


In [167]:
ft = torch.Tensor([0, 1, 2])
print(ft)
print(ft.dim())
print(ft.shape)

tensor([0., 1., 2.])
1
torch.Size([3])


In [168]:
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).dim())
print(ft.unsqueeze(0).shape)
print()
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).dim())
print(ft.unsqueeze(1).shape)

tensor([[0., 1., 2.]])
2
torch.Size([1, 3])

tensor([[0.],
        [1.],
        [2.]])
2
torch.Size([3, 1])


In [169]:
# View 로도 동일한 결과 가능
print(ft.view(1, -1))
print(ft.view(1, -1).shape)
print(ft.view(-1, 1))
print(ft.view(-1, 1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### Type Casting

Data type | dtype
|---|---|
8-bit integer (unsigned) | `torch.uint8`
8-bit integer | `torch.int8`
16-bit integer | `torch.int16` or `torch.short`
32-bit integer | `torch.int32` or `torch.int`
64-bit integer | `torch.int64` or `torch.long`
16-bit floating point | `torch.float16` or `torch.half`
32-bit floating point | `torch.float32` or `torch.float`
64-bit floating point | `torch.float64` or `torch.double`

`Type Casting` 자료형을 변환하는 것

In [170]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)
print(lt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])


In [171]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### Concatenate

두 텐서를 `연결(concatenate)`

In [172]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])
print(x)
print(x.shape)
print(y)
print(y.shape)

tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])
tensor([[5., 6.],
        [7., 8.]])
torch.Size([2, 2])


In [173]:
print(torch.cat([x, y], dim=0)) # dim=0은 첫번째 차원을 늘리라는 의미
print(torch.cat([x, y], dim=0).shape)
print()
print(torch.cat([x, y], dim=1))
print(torch.cat([x, y], dim=1).shape)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
torch.Size([4, 2])

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])
torch.Size([2, 4])


### Stacking

`Stacking` `연결(concatenate)`을 하는 또 다른 방법

In [174]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])
print(x.dim())
print(x.shape)

1
torch.Size([2])


In [175]:
print(torch.stack([x, y, z]))
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0)) # 위와 동일한 연산
print(torch.stack([x, y, z]).dim())
print(torch.stack([x, y, z]).shape)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
2
torch.Size([3, 2])


In [176]:
print(torch.stack([x, y, z], dim=1))
print(torch.stack([x, y, z], dim=1).dim())
print(torch.stack([x, y, z], dim=1).shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
2
torch.Size([2, 3])


### ones_like / zeros_like

- `ones_like` 동일한 크기(shape)지만 1으로만 값이 채워진 텐서를 생성
- `zeros_like` 동일한 크기(shape)지만 0으로만 값이 채워진 텐서를 생성

In [177]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [178]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### In-place Operation

덮어쓰기 연산

In [179]:
x = torch.FloatTensor([[1, 2], [3, 4]])
print(x.mul(2.)) # 곱하기 2를 수행한 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [180]:
print(x.mul_(2.))  # 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
